### ISSUE TITLE
AUR/Nix package

### ISSUE THREAD

**Issue by Soliprem** [ggozad/oterm#16]
it'd be nice, since ollama is present on the AUR, to make an oterm AUR package. From what I understand, it shouldn't be too hard. In the future maybe nix would be nice, too?

**Comment by ggozad** [comment]
I am not using either so would find it hard to keep maintaining those. But I would be more than happy to accept a PR if you feel like it.

**Comment by DanielChesters** [comment]
Hi, I'd just add an PKGBUILD on AUR : https://aur.archlinux.org/packages/oterm

**Comment by Soliprem** [comment]
That settles it for the AUR. For nix, I'm absolutely ignorant about it, so I can't do much with it

**Comment by ggozad** [comment]
@DanielChesters Thank you that's awesome!
I would guess that this would be best done as a GitHub action. I need to make one for `brew`, @DanielChesters would you be willing to do the work to automate creating the PKGBUILD on release?

**Comment by suhr** [comment]
Here's a flake for Nix: https://gist.github.com/suhr/49139b2a2b18818cc5a967c0f2b1bfcb.

**Comment by ggozad** [comment]
@suhr Thanks for this!
So now we have AUR and Nix 🎉
I would really like to finish this, having an easy update path for Arch and Nix would be awesome.

Ideally there should be an automatic way to update both when a new version is released. For example, for brew on MacOS I use https://github.com/tdsmith/homebrew-pypi-poet which will parse the package on PyPI, extract pinned dependencies, hashes etc and give me the formula. You can see this here:  https://github.com/ggozad/homebrew-formulas/blob/main/Formula/oterm.rb

 Is there something similar for Arch and Nix?

If we had something like that, we could just add it to GitHub actions and automate the process. 
Otherwise I would have to rely on you committing to perform any updates every time I make a new release which is fine but awkward long-term...

**Comment by suhr** [comment]
> Is there something similar for Arch and Nix?

The `flake.nix` is something you put into the root of the project, so it's always up to date with the project. I can also make a package in nixpkgs, and nixpkgs has a bot that tracks updates.

**Comment by ggozad** [comment]
@suhr is this now automatically maintained? Can I close this?

**Comment by suhr** [comment]
Sure.

**Comment by gaelj** [comment]
@ggozad just an FYI - upon @suhr's request, ownership of the nixpkg for `oterm` [is in the process of being transferred to myself](https://github.com/NixOS/nixpkgs/pull/371271).

**Comment by ggozad** [comment]
Thank you @suhr for everything and thank you @gaelj for taking over :)
