### ISSUE TITLE
Unable to copy and paste multi lines into the message box

### ISSUE THREAD

**Issue by cheuk-cheng** [ggozad/oterm#3]
Hi.  When I copy some multi-line text and try to paste it into oterm's message box then press <enter> only the first line is pasted. How can I copy and paste text blocks which I have copied from other apps into oterm?
Thanks.

**Comment by ggozad** [comment]
Oh that's a fun one! I am guessing the input widget does not allow for multi-line, I will check it out, thanks!

**Comment by denehoffman** [comment]
The recently added [TextArea](https://textual.textualize.io/widgets/text_area/) widget should allow for this, although I'm not sure how it would be best implemented.

**Comment by ggozad** [comment]
> The recently added [TextArea](https://textual.textualize.io/widgets/text_area/) widget should allow for this, although I'm not sure how it would be best implemented.

Yep. We use TextArea in the model selection when you create a new chat.
Its looks are a bit too much for an input field I think.
Having a toggle button that switches between TextArea and Input is the only idea I came up with (and then overriding what happens on paste so that an input can change to texture). 

But if there are other ideas I am all ears.

**Comment by cheuk-cheng** [comment]
Thanks ggozad.  Also, it will be nice to have an optional way of letting users press <shift-enter> (for example) to execute the chat since multi-line text inputs can contain <enter>.

**Comment by cheuk-cheng** [comment]
Hi ggozad.  Thanks for implementing the new functionality so quickly.  It is working great here.
