### ISSUE TITLE
Can't forget chat when the input field is not selected

### ISSUE THREAD

**Issue by suhr** [ggozad/oterm#34]
So if you click on a chat tab then you can't close the chat until you click on the message field.

**Comment by ggozad** [comment]
I spent some time looking at this. Tried to move the keyboard bindings to the Tab panes so that you could do rename or forget before focusing the chat container.
Unfortunately it turns out Tab Panes do not support keyboard bindings. Will keep this open in case I find a different way of doing this properly.

**Comment by yilmaz08** [comment]
@ggozad I can add a auto-focus on the FlexibleInput if the activated tab changes. This doesn't solve the core problem but it would solve the need to click the input field.

But I am not sure maybe an auto-focus is not wanted.

**Comment by ggozad** [comment]
@yilmaz08 I think autofocus makes sense here. Does it make navigation difficult if you have more than a couple chats?

**Comment by yilmaz08** [comment]
@ggozad If you were navigating with arrow keys, it would be so annoying but if you are using something like ctrl+tab or clicking tabs it is better. That's why I wasn't sure if it is wanted

**Comment by yilmaz08** [comment]
After testing, it is not that annoying but still not good since you need to press shift+tab every time

**Comment by ggozad** [comment]
This has now been resolved through the command palette.
