### ISSUE TITLE
copy to clipboard "code"

### ISSUE THREAD

**Issue by amonpaike** [ggozad/oterm#69]
It would simply be convenient to be able to copy only code text when it is output by an ai, or even to be able to select portions of text so you can copy it in the classic way with ctrl+c

my suggestion is a bit too obvious, but from the first uses I found it limiting not being able to select and copy portions of text..

**Comment by ggozad** [comment]
Hey there!
I think we need a copy/paste mention in the README, as this comes up very often... Perhaps this is a good opportunity for one, would appreciate it if someone comes up with a pull request on the README.

Copy pasting in terminal apps is tricky because both the terminal and the app are trying to handle mouse and keyboard interactions. This very much depends on the terminal too, so something that works for some might not work for all.

Typically terminals support a modifier key that allows selection. For example:

* iTerm Hold the OPTION key.
* Gnome Terminal Hold the SHIFT key.
* Windows Terminal Hold the SHIFT key.

Another alternative is to do something like what is suggested in #67 .

**Comment by amonpaike** [comment]
Hi buddy! I really like oterm, it has potential.
I'm using Windows, the suggestions you gave me to use shift are unusable, I'll give you a couple of screenshots..
This is the selection on code:  as you can see, it does not follow the scrolling but selects everything
<img width="663" alt="image" src="https://github.com/ggozad/oterm/assets/884282/633b9cfe-e540-4304-87c6-d61242c31516">

And when I paste it's even worse, practically unusable..

<img width="851" alt="image" src="https://github.com/ggozad/oterm/assets/884282/d3941869-0ccb-4478-995a-ec602375a273">

**Comment by amonpaike** [comment]
I understand that it might be complicated for you with the code, but perhaps the quickest thing could be the usual symbol that when you click on it put in the clipboard the portion of code that goes from the three initial quotes to the three final quotes that the AI usually uses to indicate a portion of code
