### ISSUE TITLE
Copying text output

### ISSUE THREAD

**Issue by azthec** [ggozad/oterm#8]
Hello, I am trying to copy and paste from oterm and I seem to be unable to do do any selections at all in the first place.
Is there something I am missing or is this not a current feature

**Comment by ggozad** [comment]
You can copy a message by simply clicking on it. You will see a visual brief "flash" to indicate the copy. 
But that's basically all the copying you can do currently.
This is because of way textual, the underlying framework that oterm is using, handles keyboard/mouse interactions with the app.

If this does not cover you, let me know of what you would like to copy and how and we'll try to figure out a way.
