### ISSUE TITLE
Connection refused if OLLAMA_HOST is set to 0.0.0.0 without a port

### ISSUE THREAD

**Issue by filipjanevski** [ggozad/oterm#88]
If the `OLLAMA_HOST` env variable is set to `0.0.0.0` when oterm tries to fetch the models from `http://0.0.0.0/api`, it crashes with connection refused error. In Ollama if you set the variable without a port, it serves on the default port 11434. Maybe you can add a check to see if the `OLLAMA_HOST` env variable contains a port, or just default to 11434.

**Comment by ggozad** [comment]
Hey Filip,
Apologies for the late reply.
To be honest, `OLLAMA_HOST` is a bit of a misnomer. Like you suggest, it should refer to the host only not necessarily the port. 
However it's included as such only because it is supported by the official Ollama client (and used as an env variable when interacting with the Ollama server. While I agree that it should behave the way you want it to, I am a bit reluctant to redefine it even if it is to "fix" it.

**Comment by filipjanevski** [comment]
I think you are right, this should be addressed in the Ollama implementation. I also think it is a bad practice to add a port in the background if you don't include one. I will close this issue since it is not really related to this app.
